# Dump the pickle files generated by the individual database records
import pickle, glob

# open each filename and print the contents
for filename in glob.glob('*.pkl'):
    with open(filename, 'rb') as pickleFile:
        record = pickle.load(pickleFile)
        print(filename, '=>\n ', record)

# fetch only Sue's name
with open('sue.pkl', 'rb') as suePickle:
    print(pickle.load(suePickle)['name'])
    